[theme]
primaryColor             = "#7C3AED"
backgroundColor          = "#F0F2FF"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#1E1B4B"
font                     = "sans serif"

[server]
headless         = true
enableCORS       = false

[browser]
gatherUsageStats = false